version: '2.4'

services:
  kibana:
    build: .
    ports:
    - '5601'
    depends_on:
    - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      discovery.type: single-node
      xpack.monitoring.collection.enabled: 'true'
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: -XshowSettings:vm

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - elasticsearch:/usr/share/elasticsearch/data
    ports:
    - '9200'

volumes:
  elasticsearch:
    driver: local
